//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankSystem.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم حساب.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكالات.
        /// </summary>
        public static string Agencies {
            get {
                return ResourceManager.GetString("Agencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوكالة.
        /// </summary>
        public static string AgencyName {
            get {
                return ResourceManager.GetString("AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنوك.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابات البنوك.
        /// </summary>
        public static string BanksAccount {
            get {
                return ResourceManager.GetString("BanksAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة تأكيد.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء وكالة.
        /// </summary>
        public static string CreateAgency {
            get {
                return ResourceManager.GetString("CreateAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء بنك.
        /// </summary>
        public static string CreateBank {
            get {
                return ResourceManager.GetString("CreateBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حسابات بنكية.
        /// </summary>
        public static string CreateBankAccount {
            get {
                return ResourceManager.GetString("CreateBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء عملة.
        /// </summary>
        public static string CreateCurrency {
            get {
                return ResourceManager.GetString("CreateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملات.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز العملة.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من أنك تريد حذف البنك.
        /// </summary>
        public static string DeleteBankConfirm {
            get {
                return ResourceManager.GetString("DeleteBankConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل وكالة.
        /// </summary>
        public static string EditAgency {
            get {
                return ResourceManager.GetString("EditAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل البنك.
        /// </summary>
        public static string EditBank {
            get {
                return ResourceManager.GetString("EditBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل  حسابات البنوك.
        /// </summary>
        public static string EditBanksAccounts {
            get {
                return ResourceManager.GetString("EditBanksAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل عملة.
        /// </summary>
        public static string EditCurrency {
            get {
                return ResourceManager.GetString("EditCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايميل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجليزي.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بالعالم.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرع البنك.
        /// </summary>
        public static string MainBranch {
            get {
                return ResourceManager.GetString("MainBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
